# Jykell configuration
markdown: redcarpet
highlighter: pygments
paginate: 5
language: 'de-de'

# Website info
name: 'Hannes Diem'
description: '...über die Musik, das Leben und den ganzen Rest'

# Author's info
author: 'Casper McFadden'
# edit 'categories' in the front matter of every post to match this username
username: casper
bio: 'A paranormal expert and his daughter bunk in an abandoned house populated by 3 mischievous ghosts and one friendly one.'
location: 'Maine, USA'
url: 'http://hannesdiem.de'

short_url: 'hannesdiem.de'
google_analytics: UA-65675428-2
disqus: diemmusik
# edit baseurl to simply '/' if using as your personal page (instead of a project page)
baseurl: /

# Permalinks
permalink: /:title/
# permalink: /author/:username
# permalink: /tag/:tag

# fb_app_id: 727902270677409


# gems and other configs
gems: [jekyll-paginate]
exclude: [vendor]

# Additional settings available on the front-matter
# Site logo in the index.html (as in demo.ghost.io)
# Author's page cover in _layouts/author.html
# The same for page.html and tag.html layouts
# Post's page cover as a per-post basis _posts/...
# Disqus comments as a per-post basis
# ...


# Settings for builing master branch with travis-ci
# with jekyll-travis

# Settings for deploy rake task
# Username and repo of Github repo, e.g.
# https://github.com/USERNAME/REPO.git
# username defaults to ENV['GIT_NAME'] used by Travis
# repo defaults to USERNAME.github.io
# Branch defaults to "source" for USERNAME.github.io
# or "master" otherwise
safe: false
lsi: false
username: Xiphe
repo: hannesdiem.de
branch: master
destination: ../hannesdiem.de-pages/
production_url:  http://hannesdiem.de
source_url:      https://github.com/Xiphe/hannesdiem.de

exclude:
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - changelog.md
  - "*.Rmd"
  - vendor
  - .travis.yml
  - GHOST.txt
  - LICENSE.txt
